### ISSUE TITLE
How to resolve the problem _diagramMaker.default is not a constructor"

### ISSUE THREAD

**Issue by oo8549625** [awslabs/diagram-maker#12] opened 2020-10-07 09:54 UTC
environment
diagram-maker: 1.0.0
parcel: 1.12.4
npm: 6.14.8
node: v14.8.0

index.html
```
<html>
<body>
  <script src="./index.js"></script>
  <div id="root"></div>
</body>
</html>
```
index.js
```
import DiagramMaker, { ConnectorPlacement } from 'diagram-maker';
import 'diagram-maker/dist/diagramMaker.css';
const diagramMaker = new DiagramMaker(
    'root',
    {
        options: {
            connectorPlacement: ConnectorPlacement.LEFT_RIGHT
        },
        renderCallbacks: {
            // Example Render Callback that displays the id within the node
            node: (node, container) => {
                const newDiv = document.createElement('div');
                const newContent = document.createTextNode(node.id);
                newDiv.appendChild(newContent);
                newDiv.classList.add('example-node');
                if (node.diagramMakerData.selected) {
                    newDiv.classList.add('selected');
                }
                container.innerHTML = '';
                container.appendChild(newDiv);
                container.addEventListener('click', myAwesomeEventListener);
            },
            // Example destroy callback that removes the event listener
            destroy: (container) => {
                container.removeEventListener('click', myAwesomeEventListener);
            }
        }

    },
    // optionalParams // { initialData, eventListener, consumerRootReducer, consumerEnhancer }
);
```

**Comment by sameergoyal** [comment] 2020-10-07 16:33
Duplicate of https://github.com/awslabs/diagram-maker/issues/13.

**Closed by sameergoyal** 2020-10-07 16:33 UTC
