### ISSUE TITLE
Undo/Redo : wrong node position

### ISSUE THREAD

**Issue by JohnCyberWick** [awslabs/diagram-maker#54] opened 2021-05-21 13:48 UTC
Hello,

Whenever I use the undo/redo feature, the nodes are not correctly positionned to their last known location. This seems to happen when you undo everything (sometimes before, it's not 100% consistent).

To reproduce: you can use the [demo](https://awslabs.github.io/diagram-maker/examples/LeftRightRectangular.html)
1. Create three nodes
2. Move them around (away from their initial position)
3. Undo everything
4. Redo everything
5. The nodes are back to their initial position (when they were created)

Expected behavior: the node should be back at their last known location.

Observed on: Ubuntu 20.04 with Firefox 78 ESR.

Best regards

**Comment by sameergoyal** [comment] 2021-06-10 08:37
Apologies for the late response. 

The way undo redo functionality is implemented in Diagram Maker is by only marking some actions that go into the undo redo history. Those are create & delete actions, so any other changes are not retained inside the undo redo history. See the relevant code here: https://github.com/awslabs/diagram-maker/blob/master/src/state/middleware/undoMiddleware.ts#L11-L27.

We can internally start tracking all actions instead of a few actions, the problem is that when moving nodes, it doesnt generate a single action, but a series of actions, and it can take up the entire stack of history and we have no good way of coalescing those actions for purposes of undo redo. We need to find a way to coalescing the move actions and then expose either a configuration option or change the default behavior to start tracking all actions.

**Comment by tracfren** [comment] 2022-08-25 21:46
Sorry, we are not planning to act on this request in any timely manner and will be closing this issue. Thank you.

**Closed by tracfren** 2022-08-25 21:46 UTC
Labels: enhancement
